### ISSUE TITLE
Kottans + Pivorak = <3

### ISSUE THREAD

**Issue by g3d** [Kottans/kottans-ongoing-projects#11]
This issue is about 
+ [x] Course
+ [ ] Event
+ [x] Project
+ [ ] Other

By/for
+ [x] kottans
+ [x] non-kottans

Subject: kottans + pivorak course with personal mentors and contribution to open source

Term/duration: min 8 weeks, starting from May

Keywords: offline, lviv, ruby, js, 

We're going to combine traditional course and work in the team with bigger mentors amount on open source/new project that would be useful for non-IT organizations (NGO, etc).

Tasks:
+ [x] Find mentors
+ [ ] Assemble final program
+ [ ] Announce registration 
+ [ ] Review test tasks
+ [ ] Start course

**Comment by sudodoki** [comment]
🎉 👍 sounds good. Might want to use this thread as another point to communicate terms / registration / progress, etc. Any particular help you might be needing from others?

**Comment by g3d** [comment]
@sudodoki we have thread in pivorak slack for communication between mentors, discussing final program, will update issue after offline meeting (happen between 18 & 21). Need PR support from kottans team.

**Comment by suchov** [comment]
@g3d we can create a gitter channel for students & mentors if you need

**Comment by g3d** [comment]
Made an opening during yesterday's pivorak, https://pivorak.com/ruby-course

**Comment by g3d** [comment]
@sudodoki @suchov could you please share this https://pivorak.com/ruby-course together with other kottans?

**Comment by suchov** [comment]
@g3d sure

**Comment by sudodoki** [comment]
AFAIK, this is either over or almost over. @g3d any write-ups / thoughts you might be willing to share with community? Either here or on some platform, like DOU?

**Comment by g3d** [comment]
Hey guys, we finished the course. Here is post with photos: https://www.facebook.com/pivorak.ruby.course/posts/155757251644109, give them a try, find kottans logo on certificates/t-shirts.

**Comment by sudodoki** [comment]
Closing this for now then. ^_^
