### ISSUE TITLE
Kyiv AI:MA study group

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans-ongoing-projects#12]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [X] Other [Study Group]

By/for
+ [X] kottans
+ [X] non-kottans

Subject: Study group / reading club to go over [AI: A Modern Approach](http://aima.cs.berkeley.edu/) and exercises.

Term/duration: depends on pace of reading. Initial assumption – we go with one chapter a week. It will span 27 weeks at least.

Keywords: offline, Kyiv, reading club, AI

Some things are still TBD.
We don't have a stated venue for this. Might be some coworking.

We don't have schedule set for this. I assume we gonna assemble once a week (Sunday?) and going over exercises/discussing questions, etc for 1-2 hours.

If you would like to try to pick this up, drop me a line at smd.deluzion@gmail.com and leave a comment in this issue.

**Comment by AMashoshyna** [comment]
I'd like to participate

**Comment by fitnessyulya** [comment]
I'd like too

2017-04-24 23:07 GMT+03:00 Anastasiya Mashoshyna <notifications@github.com>:

**Comment by suchov** [comment]
I'm in!

**Comment by Alimova** [comment]
+1 
Are there any requirements? Books to read before course, things to learn?

**Comment by Veligura** [comment]
+1

**Comment by sudodoki** [comment]
@Alimova 
>Books to read before course, things to learn

Dunno, depends on what you know already. Baseline is that no preliminary knowledge is required, but be ready to cover extra things if necessary on your own. 

>Are there any requirements

Previous club required 1-5 hours of work weekly. So, you'll need that. Not sure, how this one would turn out.

**Comment by zonzujiro** [comment]
👍 +1

**Comment by mgdskr** [comment]
I'd like to join

**Comment by LiliVia** [comment]
+1 :)

**Comment by Cath-kb** [comment]
+1

**Comment by sudodoki** [comment]
There's already more people willing to join than spots available. 
There are also people from SICP reading club that are in 100%.
It might be that we'll have to limit participants based on time of application, sorry about that.
And FYI, there's edx course that covers most of the book's topics https://www.edx.org/course/artificial-intelligence-ai-columbiax-csmm-101x-0

**Comment by sudodoki** [comment]
Actually, something came up so yeah, it's all good, I think everyone who left comment can fit into the group. 

>If you would like to try to pick this up, drop me a line at smd.deluzion@gmail.com and leave a comment in this issue.

I got only 2 emails so far, @fitnessyulya, @suchov, @Alimova, @Veligura, @mgdskr, @LiliVia, @Cath-kb please send it.

**Comment by wack17s** [comment]
+

**Comment by AlexPurhalo** [comment]
+1

**Comment by sudodoki** [comment]
Please, check your inbox for initial coordination email.

**Comment by AMashoshyna** [comment]
[Intro to Artificial Intelligence Class on Udacity](https://www.udacity.com/course/intro-to-artificial-intelligence--cs271) by Peter Norwig & Sebastian Thrun
I'm listening to Lesson 1 and I like the mentor very much so far

**Comment by sudodoki** [comment]
Closing this issue. You are welcome to do same thing in different [thread](https://github.com/Kottans/kottans-ongoing-projects/issues/new) if you want to. Coordination for this affair will go through other means, thus I'm closing this issue.
