### ISSUE TITLE
Kottans frontend course

### ISSUE THREAD

**Issue by suchov** [kottans/kottans-ongoing-projects#14]
This issue is about 
+ [X] Course
+ [ ] Event
+ [ ] Project
+ [ ] Other

By/for
+ [X] kottans
+ [ ] non-kottans

Subject: Course for future Kottans that start from very beginning learning front-end

Term/duration: December 1st 2107 - December 1st 2018

Keywords: offline, Kiev, CSS, HTML, JS, Frameworks, HTTP, Git, Console, Linux Basics, Spead Reading/Learning

~~What do we propose and what do we need to reach the goal.~~
Plan and support of the learning tribe.

**Comment by Avvata** [comment]
Hi, guys! How can I register for this course?

**Comment by AMashoshyna** [comment]
Hi @Avvata! The registration for this course is not yet open. Please follow @kottans_org on Twitter for updates.

**Comment by suchov** [comment]
@Avvata you even can start doing the test tasks https://github.com/Kottans/frontend but about registration we'll announce later on Twitter, that's true.

**Comment by Avvata** [comment]
I've understood. Thank you!

**Comment by suchov** [comment]
The course has successfully finished.
