### ISSUE TITLE
NodeSchool events

### ISSUE THREAD

**Issue by suchov** [kottans/kottans-ongoing-projects#15]
This issue is about 
+ [ ] Course
+ [X] Event
+ [ ] Project
+ [ ] Other

By/for
+ [ ] kottans
+ [X] non-kottans

Subject: [https://nodeschool.io/](https://nodeschool.io/)

Term/duration: We are planning the first event, will be updated.

Keywords: Offline, Kiev

Regular NodeSchool events.

**Comment by suchov** [comment]
https://github.com/nodeschool/kyiv/issues

**Comment by zonzujiro** [comment]
This is a dead event, IMO. No need in continue

**Comment by suchov** [comment]
Wo-ho-ho. The rest of the world does not totally agree with you. https://nodeschool.io/
I think it really depends on how active is the community in the city...
