### ISSUE TITLE
Tech Terms Advent Calendar 2017

### ISSUE THREAD

**Issue by AMashoshyna** [kottans/kottans-ongoing-projects#16]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [X] Other

By/for
+ [X] kottans
+ [X] non-kottans

#### Subject: Tech Terms Advent Calendar

Term/duration: 01.12.2017 - 25.12.2017

Keywords: online, puzzles

Idea by @sudodoki 
Tech advent calendar initiative comes from traditional Christian [Advent calendars](https://en.wikipedia.org/wiki/Advent_calendar). In tech community advent calendars usually include interesting posts, quizzes or challenges posted daily in the same time of the year. Some ongoing and past advent calendars:
- [Advent of Code](http://adventofcode.com/)
- [24 Pull Requests](https://24pullrequests.com/)
- [Web Advent Calendar](http://web.advent.today/)

Kottans-flavored Tech Terms Advent Calendar shall include daily tasks with two or more technical terms, which are often used in the same context and thus often confused. The challenge will be to explain what the terms have in common (if they do) and how they are different (if they are).  Some related links on the subject may be posted next day.
The terms will be related to web development and beyond. The challenges will be posted in Kottans twitter and gitter.
This initiative is mostly targeted at newcomers.
December 1 https://twitter.com/kottans_org/status/936558165692436480
December 2 https://twitter.com/kottans_org/status/936903223746555904
December 3 https://twitter.com/kottans_org/status/937298531056046080
December 4 https://twitter.com/kottans_org/status/937628307562094594
December 5 https://twitter.com/kottans_org/status/937988830086549505
December 6 https://twitter.com/kottans_org/status/938344076520419329
December 7 https://twitter.com/kottans_org/status/938714262175961088
December 8 https://twitter.com/kottans_org/status/939073419131473920
December 9 https://twitter.com/kottans_org/status/939436585728258048
December 10 https://twitter.com/kottans_org/status/939826648656044033
December 11 https://twitter.com/kottans_org/status/940146791105867776
December 12 https://twitter.com/kottans_org/status/940523082887901184
December 13 https://twitter.com/kottans_org/status/940887712814510080
December 14 https://twitter.com/kottans_org/status/941241184399364102
December 15 https://twitter.com/kottans_org/status/941612911604137984
December 16 https://twitter.com/kottans_org/status/941978857661501442
December 17 https://twitter.com/kottans_org/status/942354813429403648
December 18 https://twitter.com/kottans_org/status/942703320388521984
December 19 https://twitter.com/kottans_org/status/943059715650674689
December 20 https://twitter.com/kottans_org/status/943435429390536706
December 21 https://twitter.com/kottans_org/status/943791613456809984
December 22 https://twitter.com/kottans_org/status/944158418725736448
December 23 https://twitter.com/kottans_org/status/944528710530732032
December 24 https://twitter.com/kottans_org/status/944912511530405888
December 25 https://twitter.com/kottans_org/status/945231502694109184

**Comment by sudodoki** [comment]
December 1 https://twitter.com/kottans_org/status/936558165692436480
December 2 https://twitter.com/kottans_org/status/936903223746555904
December 3 https://twitter.com/kottans_org/status/937298531056046080
Not sure if need to duplicate those here 🤔

**Comment by AMashoshyna** [comment]
@sudodoki good idea, thank you!

**Comment by AMashoshyna** [comment]
Calendar is done for this year

**Comment by suchov** [comment]
thank you @AMashoshyna & @sudodoki for this adventure
