### ISSUE TITLE
Kyiv ESL study group

### ISSUE THREAD

**Issue by sudodoki** [kottans/kottans-ongoing-projects#17]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [X] Other [Study Group]

By/for
+ [X] kottans
+ [X] non-kottans

Subject: Study group / reading club to go over [The Elements of Statistical Learning](http://www.springer.com/gp/book/9780387848570) (ESL).

Term/duration: depends on pace of reading. Initial assumption – we go with one chapter a week. It will span 18 weeks at least. I think we are going to start in January.

Keywords: offline, Kyiv, reading club, Statistics

Some things are still TBD.
We don't have a stated venue for this. Might be some coworking.

We don't have schedule set for this. I assume we gonna assemble once a week (Sunday?) and going over exercises/discussing questions, etc for 1-3 hours.

If you would like to try to pick this up, drop me a line at smd.deluzion@gmail.com and leave a comment in this issue. There are already some people from previous courses who want to pick this up. Group size is limited.

Previously we did similar thing with [AI:MA](https://github.com/kottans/kottans-ongoing-projects/issues/12) & [SICP](https://github.com/kottans/kottans-ongoing-projects/issues/5).

**Comment by mgdskr** [comment]
👍+1

**Comment by BUsatov** [comment]
+1

**Comment by alexeymazurik** [comment]
+1

**Comment by Yevs** [comment]
+1

**Comment by h8is2w8** [comment]
+1

**Comment by sudodoki** [comment]
Ok, seems we now have all the group members. First meeting is tomorrow. Further coordination is done through telegram group. Closing this issue.

**Comment by hmlON** [comment]
@sudodoki Is there any way to get into this telegram group and into ESL study group?

**Comment by sudodoki** [comment]
@hmlON ¯\_(ツ)_/¯ sorry for not answering sooner. No.

**Comment by sudodoki** [comment]
Seems that this group is no more – on March 18 we finished [ISL](http://www-bcf.usc.edu/~gareth/ISL/) instead of ESL (ESL was too difficult for this group).
