### ISSUE TITLE
Fall 2016. Ruby.

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans-ongoing-projects#2]
This issue is about 
- [x] Course
- [ ] Event
- [ ] Project
- [ ] Other

By/for
- [x] kottans
- [ ] non-kottans

Subject: Ruby course in fall 2016.

Term/duration: 6 weeks

Keywords: offline, Kyiv, (Lviv?), (Kharkiv?), ruby, rails

We have few coaches @tilast, @ololyay, @darthrevan, @vessi. Need more coaches / guest coaches.
Work on program/test assignments/homeworks will be done [here](https://drive.google.com/folderview?id=0B65dEGRmB3VidHlyRm1iT0VwN0k&usp=sharing)

**Comment by sudodoki** [comment]
@g3d might be interested in this as well

**Comment by sudodoki** [comment]
Additional conversations happening in https://gitter.im/Kottans/ruby-slides

**Comment by sudodoki** [comment]
Maybe, just maybe, @firec0der might be interetested.

**Comment by firec0der** [comment]
I'd like to join this party but I have a lot of other activities. So, I'm not sure.

**Comment by g3d** [comment]
:+1: I'm in

**Comment by tilast** [comment]
@g3d 🎉  let's have a call on this week

**Comment by petrokoriakin** [comment]
Adding @skarm61 @SmyzerT and @iomelchenko to the thread. We are going to join the party from Kharkiv

**Comment by tilast** [comment]
wow cool news

**Comment by vessi** [comment]
here, I fixed description

**Comment by vessi** [comment]
Summary of call: 27.08.2016

+ Kharkiv Kottans will have meeting at 29.08.2016
+ Lviv was absent on call, @g3d, please connect with me separately
+ At 31.08.2016 we will agree final high-level program for courses
+ @ololyay will create description of test task
+ @vessi will create lecture about process management before 03.09.2016
+ Courses will be anounced at 10.09.2016
+ Test task will be limited to 02.10.2016
+ Courses will start at 17.10.2016

+ Next call will be established 03.09.2016

**Comment by petrokoriakin** [comment]
The meeting in Kharkiv had taken place.
- The program and the format of community driven education is clear and there should not be a lot of problems. @petrokoriakin to find a place for lectures and discuss a set of promo-events with Kharkiv coaches.
- A question from @petrokoriakin : **Is it fine to establish additional activity in the Kharkiv?** To gather real life experience and a feedback from potential audience, there is a plan to do three or four meetups during September when potential coaches can get some practice presenting separate topic from the course. With no homework - just presentation and lecture. We also can test different venues for course and see what will fit our needs.
- We definitely need to find two or more guest coaches. @petrokoriakin to contact rubyists and ask them if they want to participate. 
- A question from @zverok : **Is it ok to use github and PRs to https://github.com/Kottans/ruby-slides  for lecture structure, plan, lesson assignment high-level overview and discussions**? Or it is place for slides only but not markdown files and a brief plans? Currently it is handled in the spreadsheet, but there is not much tools for proposals etc. 
- English slides: can pull-requests with other languages be added? Or, at least, can coach use materials in whatever language he wants during the lesson/workshop?

- Looking forward for call on 03.09.2016 to discuss items above

**Comment by zverok** [comment]
Another question from @zverok: чуваки, а правда-правда надо всё тут на техническом английском обсуждать?.. Учитывая что лекции и обсуждения в чятике всё же не на нём...

**Comment by sudodoki** [comment]
Yep, that's how we roll.

**Comment by vessi** [comment]
Just as an easy explanation: this experience also should be used by San Francisco based Kottans (as far as I remember @suchov planed something like that)

**Comment by g3d** [comment]
@kushniryb will join us in Lviv

**Comment by brain-geek** [comment]
> We have few coaches @tilast, @ololyay, @darthrevan, @vessi. Need more coaches / guest coaches.

I'm in as well (Kyiv).

**Comment by suchov** [comment]
@zverok also we want to be able to share all the materials with the whole world, so ...

**Comment by sudodoki** [comment]
I assume as course already finished in 2 out of 3 cities, we can close this issue?
In case anyone needs it, some videos are available [here](https://www.youtube.com/playlist?list=PLr1siHsWN79Aj5I4e3ux-mjq7zVeTOCdp)
