### ISSUE TITLE
Job interview questions

### ISSUE THREAD

**Issue by alenakuznetsova** [kottans/kottans-ongoing-projects#20]
This issue is about 
+ [ ] Course
+ [x] Event
+ [ ] Project
+ [x] Other

By/for
+ [x] kottans
+ [ ] non-kottans

Subject: Meeting for discussing questions from job interview for future job interview

Term/duration: unknown

Keywords: offline, Kiev, JS, HTML, CSS, React, Angular etc.

What do we propose and what do we need to reach the goal:

- [list](https://docs.google.com/spreadsheets/d/1FERZIQ-8dCYGzBtNdAJH3CsTRmN4NVw5PRz41tYQdbE/edit?usp=sharing) with questions (from job interview) for discussing everybody who will be in team can add question 
- mentor who will be team lead, he/she will be asking questions and give feedback or correct answer
- group of people (one team with one team lead ~6 - 10 people)
- rules (who should answer on question, who next)

**Comment by zonzujiro** [comment]
I'm in!

**Comment by suchov** [comment]
@alenakuznetsova what do you think about moving the list to github? 
Also, what do you think about using lists https://github.com/h5bp/Front-end-Developer-Interview-Questions that already exist?
On my opinion mosk interview is a great stuff to practice but better to use real-life questions :)

**Comment by alenakuznetsova** [comment]
I agree, we can combine real-life questions, some sources with ready questions and use questions from our guys.

**Comment by LiliVia** [comment]
Great idea! I'm in too :)

**Comment by Alimova** [comment]
When is it? I would love to participate.

**Comment by alenakuznetsova** [comment]
I think we can discuss all process on Saturday (31.03.2018) and choose date

**Comment by shvaikalesh** [comment]
Count me in. I don't think we should make a list ourselves: we can use [A](https://github.com/h5bp/Front-end-Developer-Interview-Questions) or [B](https://github.com/yangshun/front-end-interview-handbook).
