### ISSUE TITLE
Study group to go over CS224n

### ISSUE THREAD

**Issue by sudodoki** [kottans/kottans-ongoing-projects#21]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [X] Other

By/for
+ [X] kottans
+ [X] non-kottans

Subject: study group to go over [CS224n](http://web.stanford.edu/class/cs224n/). This is a rather challenging course, so consider going through first week suggested reading on [syllabus page](http://web.stanford.edu/class/cs224n/syllabus.html) to figure out whether you'll be comfortable with material.

Term/duration: I would love to start sometime next week [July 18-22] and it's gonna be at least 11 weeks.

Keywords: offline, Kyiv, ML/NLP

We did try study group format before, but mostly for books ([1](https://github.com/kottans/kottans-ongoing-projects/issues/17), [2](https://github.com/kottans/kottans-ongoing-projects/issues/12)).

**What's the benefit of study group**:
- scheduling some time aside specifically for this tasks
- extra motivation
- being able to talk through most complicated parts
- understanding you are not the only one struggling :)

**What we don't have yet**:
- specific place we are going to do that in. We would either use some coworking facility (chasopys / projector were fine choices previously) or some company would generously host use
- answer to the question 'which days is it going to take place'. Previously, it did converge to saturday/sundays and 2-4 hour sessions

We are going to solve abovementioned via group chat in telegram.

**This is a kinda first-come-first-served situation as number of slots is limited** (as big study group don't work that well).

If you would like to try to pick this up, drop me a line at smd.deluzion@gmail.com and leave a comment in this issue.

**Comment by sudodoki** [comment]
Breakdown by weeks planned
```
Week1
Introduction to NLP and Deep Learning 

Week2
Word Vectors 1
Word Vectors 2
Start assignment 1

Week3
Neural Networks
Python Refresher

Week4
Backpropagation and Project Advice
Introduction to TensorFlow 
End assignment 1
Start assignment 2

Week5
Dependency Parsing 

Week6
Recurrent Neural Networks and Language Models 

Week7
Vanishing Gradients, Fancy RNNs 
[Midterm Review]
End assignment 2
Start assignment 3

Week8
Machine Translation, Seq2Seq and Attention

Week9
Advanced Attention 

Week10
Transformer Networks and CNNs

Week11
Coreference Resolution
End assignment 3

Extra [Week11 – Week XX]
[Tree Recursive Neural Networks and Constituency Parsing]
[Advanced Architectures and Memory Networks]
[Reinforcement Learning for NLP Guest Lecture]
[Semi-supervised Learning for NLP]
[Future of NLP Models, Multi-task Learning and QA Systems]
```

**Comment by mgdskr** [comment]
🔥 I am in

**Comment by Veligura** [comment]
I am in too )))

**Comment by cristaloleg** [comment]
Offline only :(

**Comment by sudodoki** [comment]
@cristaloleg you can try setting similar thing in your city

**Comment by suchov** [comment]
@sudodoki what do you think about twitting about this study group?

**Comment by mishahliba** [comment]
I am in

**Comment by sudodoki** [comment]
@DmitryOlkhovoi 
+ [x] leave a comment
+ [ ] write an email
One more thing to do

**Comment by DmitryOlkhovoi** [comment]
@sudodoki looks like I' closed Gmail too soon and it didn't send anything. Done :)

**Comment by ViktoriaSl** [comment]
+ I am in too

**Comment by sudodoki** [comment]
We are set now. First meeting is this Sunday

**Comment by yuriy-yarosh** [comment]
@sudodoki maybe there's one extra spot for me ?

**Comment by sudodoki** [comment]
@yuriy-yarosh I would personally tag you as overqualified, you sure you wanna do this? Depending on answers of two other people, we might be over the capacity, yet you are welcome to join when someone drops the group

**Comment by yuriy-yarosh** [comment]
>  I would personally tag you as overqualified

Sure, but I've got some weak spots here and there, it worth recollecting some old stuff and the theory behind it.

> Yet you are welcome to join when someone drops the group

Thanks, man.
