### ISSUE TITLE
Translate first chapter of Up&Going of YDKNJS

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#23]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [x] Other

By/for
+ [x] kottans
+ [x] non-kottans

Subject: 
Translate [Chapter 1: Into Programming](https://github.com/getify/You-Dont-Know-JS/blob/master/up%20%26%20going/ch1.md) 

Term/duration: 
I think we can start on 10.11.2018 - 11.11.2018. But this is a discussible moment.

Keywords: online/offline, translation

During a last frontend courses, we have faced with two problems:
1. Students can use JS but don't understand basic principles of the language, such as `function` vs `arrow function`, `class` with `prototype`, `var` vs `let` and `const`, etc.
2. Poor level of english of students and the absence of good translated learning materials

So let's translate first chapter of the first book from YDKJS series. For this, we should split parts of the chapter between participants. 

Also, we have two ways, which, obviously can be combined:
- offline meetings, with a great and friendly company, where we chit-chatting, drinking coffee, tea, juice, water, single malts or whatever while translating a book
- or at home, like an old lady, with cat, plaid and weather complaints

**Comment by yevhenorlov** [comment]
> or at home, like an old lady, with cat, plaid and weather complaints

I feel attacked!

On a serious note, which language do we translate to, Russian or Ukrainian? Not meaning to provoke a heated argument, just curious.

**Comment by sudodoki** [comment]
>and the absence of good translated learning materials

Just in case, there's a Ukrainian translation of Understanding ES6 https://github.com/LambdaBooks/understandinges6ua

**Comment by mgdskr** [comment]
@zonzujiro have you seen this https://github.com/azat-io/you-dont-know-js-ru

**Comment by zonzujiro** [comment]
I believe that most logical step is to continue work of LambdaBooks
