### ISSUE TITLE
Online Frontend Course 2019

### ISSUE THREAD

**Issue by suchov** [kottans/kottans-ongoing-projects#24]
This issue is about 
+ [X] Course
+ [ ] Event
+ [ ] Project
+ [ ] Other

By/for
+ [X] kottans
+ [ ] non-kottans

Subject: Frontend course that can be taken fully online

Term/duration: non stop
Keywords: online, JS, HTML, CSS, possibly some React

Let me think about that: ~~What do we propose and what do we need to reach the goal.~~

**Comment by suchov** [comment]
It's still going, the chat is here https://t.me/joinchat/A0fzFlJmLm-RUoyjMhV-_A

**Comment by suchov** [comment]
@OleksiyRudenko can you pls assign junior mentors here too pls?

**Comment by OleksiyRudenko** [comment]
@suchov If you assignees to this issue I cannot for insufficient rights

**Comment by suchov** [comment]
got it @OleksiyRudenko

**Comment by suchov** [comment]
what about now @OleksiyRudenko
