### ISSUE TITLE
RubySchool

### ISSUE THREAD

**Issue by suchov** [kottans/kottans-ongoing-projects#27]
This issue is about 
+ [ ] Course
+ [X] Event
+ [ ] Project
+ [ ] Other

By/for
+ [ ] kottans
+ [X] non-kottans

Subject: Start RubySchool movement around the world

Term/duration: Start a series of small events around the world

Keywords: Offline, in many cities.

~~What do we propose and what do we need to reach the goal.~~

**Comment by zonzujiro** [comment]
Gush 🙄 Just close it already. Who needs ruby anyway?

**Comment by AMashoshyna** [comment]
Someone's toxic this morning =)

**Comment by suchov** [comment]
https://www.youtube.com/watch?v=h6Ol3eprKiw

**Comment by zonzujiro** [comment]
19 days have passed and no one left his comment. What a shame... 😢

**Comment by zonzujiro** [comment]
27 days is gone. Looking forward to updates!

**Comment by suchov** [comment]
Don't just wait, just do it ;)

**Comment by zonzujiro** [comment]
I am terribly sorry... really...
