### ISSUE TITLE
Python Study Group

### ISSUE THREAD

**Issue by AMashoshyna** [kottans/kottans-ongoing-projects#34]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [x] Other

By/for
+ [x] kottans
+ [x] non-kottans

Subject: Study Group for Python beginners.
Term/duration: app.2 month starting on the 17th of April. Duration may be extended.

Keywords: python, study group

It is proposed to study book ["Automate Boring Stuff With Python"](https://automatetheboringstuff.com/#toc) together. The study group will meet weekly online or offline (to be discussed with the group) for review and discussions.

[Registration form](https://forms.gle/NrgS1j747UoSEdry9)

**Comment by suchov** [comment]
I'll definitely try to help where I can.
As a practical project, I can suggest to try to write some tasks for https://pythonschool.io/ :)
