### ISSUE TITLE
Free JetBrains licences

### ISSUE THREAD

**Issue by nazmariam** [kottans/kottans-ongoing-projects#35]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [x] Other

By/for
+ [x] kottans
+ [ ] non-kottans

Subject: JetBrains provides free licences for usergroups and communities 

Term/duration: each month 

Keywords: JetBrains, licence, free

JetBrains [supports](https://www.jetbrains.com/community/support/#section=communities) studying groups and communities with free licences each month (up to 3 free licenses per month for groups that gather 100+ attendees at each **monthly meeting** and free licenses for user group leader(s) (up to 2 licenses)). 
We could send request to JB, try to receive free licences for mentors and play some license-lottery between students or reward most active. Also we can use these free licences as promotional material to attract and motivate new students.

**Comment by OleksiyRudenko** [comment]
Strongly backing the above.
@suchov do you believe we could ask someone having sufficient personal capacity to investigate the topic any further?
