### ISSUE TITLE
RFC: Input ideas

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#36]
This issue is about 
+ [ ] Course
+ [X] Event
+ [ ] Project
+ [ ] Other

By/for
+ [X] kottans
+ [ ] non-kottans

Subject: We need new ideas about how to make Input more interesting for us

Term/duration: none

Keywords: Input, Kyiv

So, with @OleksiyRudenko we came to the idea, that we can add some additional part to Input conference and, probably, make it more interesting for us to contribute our time in it.

This issue is made a start for a discussion of what we can add.

The idea to start a discussion - reduce the number of talks and make two streams:
- one with talks
- other with workshops. As an example, interviewing visitors about JS all day and give feedback right after the interview

**Comment by Croftyland** [comment]
I got an idea to invite speaker from Germany. He is member of the 
@webpack core team. Will be interesting for you?

**Comment by zonzujiro** [comment]
For Input? Can be. What experience he can share with auditory?
And will he be interested in trainy/pre-trainy auditory?

**Comment by Croftyland** [comment]
Not really,he is better for more advanced audience.

In case of input,I can invite girl from Facebook with interview topic

**Comment by OleksiyRudenko** [comment]
> Not really,he is better for more advanced audience.

Perhaps he might run a workshop on fine tuning webpack config? Beside speaking on some related and even more advanced topic

**Comment by OleksiyRudenko** [comment]
But i agree on that technical conf even for beginners should be something different from INPUT aimed at those who are just entering the industry. Mix up won't work well.

Technical conf might be named e.g. INPUT: FE or INPUT: JS

**Comment by zonzujiro** [comment]
IMO, such a guy can be a good candidate for tech conf with advanced speakers.
But we should discuss this format together next time

**Comment by Croftyland** [comment]
As for me, word "Input" is not suitable for advanced speakers. We should step away from this idea

**Comment by zonzujiro** [comment]
@Croftyland RFC is about Input, jeez

**Comment by AMashoshyna** [comment]
Interviewing visitors on JS sounds good to me. Last year we also had an idea to make CV workshop. But both are probably more interesting for visitors than for us.

**Comment by OleksiyRudenko** [comment]
[Collection of topics of interest](https://docs.google.com/spreadsheets/d/1nQTwYrQR5YhMKBw3LNScPhyGMwbM7Jcwqz8zNLFjr_I/edit?usp=drivesdk) to our audience from a survey we conducted before launching INPUT

**Comment by OleksiyRudenko** [comment]
Bodya Kovalchuk:
> Паралельні виступи розбиті по категоріям (наприклад менджмент, веб, геймдев, тестування)

> coffee time з крутими спікерами

> стійка(і не одна) де є «прожарка» резюме , приходиш кладеш, через пару хв получаєш поради та критику

**Comment by OleksiyRudenko** [comment]
Alex Lapshyn:
> хочу заполнив таблицу "кем я хочу быть" получить 1) контакты людей, которые могли бы ответить предметно на вопросы по теме
> 2) контакты людей из компаний, в которых есть открытые вакансии джуновские по этому профилю
> 3) персонального ментора

**Comment by OleksiyRudenko** [comment]
Anna Alymova:
> Разработчик порнхаба в маске рассказывает как он туда попал?

**Comment by suchov** [comment]
https://github.com/kottans/kottans-ongoing-projects/issues/38

**Comment by OleksiyRudenko** [comment]
@suchov how 'bout renaming this ticket as "INPUT 3" and reopening it? )
