### ISSUE TITLE
Core meeting agenda

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#37]
Where: Star
When: 22/02 15:00

During the next meeting we should discuss:

- a written procedure of how to collaborate with people, who want to conduct event
- Input conference - additional ideas https://github.com/kottans/kottans-ongoing-projects/issues/36
- conference for skilled developers
- future of the platform
- watching-party project in collaboration with RR and FB DevC
- Some small activity in military NATO school

**Comment by AMashoshyna** [comment]
Kottans FB support - goals and steps

**Comment by OleksiyRudenko** [comment]
DevOps and/or GitHub/GitLab backed conf

**Comment by OleksiyRudenko** [comment]
Vacancy posts principles

**Comment by Croftyland** [comment]
Patreon

**Comment by zonzujiro** [comment]
Final agenda:

## Conferences
1) Input - additional ideas https://github.com/kottans/kottans-ongoing-projects/issues/36
2) Conference for skilled developers @zonzujiro 
3) DevOps and/or GitHub/GitLab backed conf, joint with [Fest Group](http://fest.group/) or [fwdays](https://fwdays.com/) @OleksiyRudenko 

## Website, SMM and social platforms
1) Kottans FB support - goals and steps @AMashoshyna 
2) Vacancy posts principles @OleksiyRudenko
3) Docusaurus @Croftyland 

## Platform
1) Future of the platform @zonzujiro 
2) A written procedure of how to collaborate with people, who want to conduct event 
3) Watching-party project in collaboration with RR and FB DevC @zonzujiro 
4) Some small activity in military NATO school @zonzujiro 

## Other
1) Patreon @Croftyland

**Comment by AMashoshyna** [comment]
Action points:

## Platform

1. Collect topics for watching-party project @zonzujiro 
2. Create questions for students in military school @AMashoshyna 
3. Discuss rules for the chat with communities @OleksiyRudenko @zonzujiro
4. The written procedure of event - necessary data https://telegra.ph/Dannye-dlya-nachala-provedeniya-02-22
    - create the form in google from questions - @OleksiyRudenko 
    - add the link to form to the site @zonzujiro 
    - convert necessary data to documentation - after next event

## Website, SMM and social platforms

1. Create letter to FB @suchov 
2. List of content for FB: @AMashoshyna @suchov 
    - crossposting from Radio
    - events in calendar
    - photos from events
    - postmortem after events
3. Create rules for Radio Kottans:
    - rules and example for vacancies @zonzujiro 
    - rules for links for the Radio @AMashoshyna 
4. Publish Docusarus - @Croftyland 
    - basic list of content https://telegra.ph/Spisok-kontenta-dlya-dokuzavra-02-22

## Conferences
