### ISSUE TITLE
Event in Kyiv Military Lyceum named after Ivan Bogun

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#39]
**This issue is about** 
+ [ ] Course
+ [x] Event
+ [ ] Project
+ [ ] Other

**By/for**
+ [x] kottans
+ [x] non-kottans

**Subject:** Some event in military school

**Term/duration**: one or several lectures

**Keywords**: offline, one-time event

**Information:**
Create an event for scholars from military school.
The event will be at some weekend.
We can choose the day by ourselves.
We will have crossposting with RR, this school also will make some article.
And probably NATO also will have some article about this event.

Link to agenda - https://github.com/kottans/kottans-ongoing-projects/issues/37

**Additional links:**
1. https://www.kmu.gov.ua/news/u-kiyevi-startuvav-nacionalnij-oboronnij-hakaton
2. http://kvl.mil.gov.ua/2020/02/20/%D0%BC%D1%96%D0%B6%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%B0-%D1%81%D0%BF%D1%96%D0%B2%D0%BF%D1%80%D0%B0%D1%86%D1%8F-4/

@AMashoshyna can you provide information when you will give form? :)

**Comment by Croftyland** [comment]
@zonzujiro can you figure out:
1. When school is out for holidays
2. Should lectures be concentrated in a dedicated programme area
3. Can we tell about web technologies

**Comment by Croftyland** [comment]
I'm trying to find out more information about this lyceum and their level of programming knowledge. On Wednesday will give further details

**Comment by AMashoshyna** [comment]
Please find the attached link to form draft. Feedback would be highly appreciated. 
As for subjects of possible lectures, based on discussion with @Croftyland  we could do something like:

1. Meta: asking right questions, looking for information, community, tooling
2. How the web works: what happens when you type google.com in your browser, with the accent on Chrome Dev tools(?)
3. AI workshop (image recognition)
4. Data science intro

https://forms.gle/Zgqzc7LdBUq32EBu8

**Comment by zonzujiro** [comment]
@AMashoshyna looks great!

1. "Оціни свої навички володіння комп'ютером:" - lets remove last option, because we have a next section with it
2. Missprint here - "Code, WebStrom, Atom тощо7"
3. Які терміни з наведених тобі знайомі (можеш пояснити власними словами)
  - should be checkbox
  - what is "Rayquaza"? :) https://www.pokemon.com/us/pokedex/rayquaza?
4. Які теми, пов'язані з програмуванням та компютерами, тобі цікаві: - I will suggest reaplce answers with topics, on which we can conduct an event

**Comment by AnastasiiaMashoshyna** [comment]
@zonzujiro made fixes, thanks!
Yes, it's pokemon's name. Just to make sure the applicants only check what they actually know.

**Comment by zonzujiro** [comment]
I have sent form to RR at Monday.
Waiting for response

**Comment by zonzujiro** [comment]
Till this day there is no answers in our form, so we can move this into backlog.
