### ISSUE TITLE
Fall 2016. Kottans Meetups in SF

### ISSUE THREAD

**Issue by suchov** [Kottans/kottans-ongoing-projects#4]
This issue is about 
+ [ ] Course
+ [x] Event
+ [ ] Project
+ [ ] Other

By/for
+ [x] kottans
+ [x] non-kottans

Subject: Kottans - who we are, what ppl are interested in.

Term/duration: 2-3 hours

Keywords: offline, SF, JS, Ruby, Python

Work on the program of the event(I think my presentation will be the main one). Looking for a place.
Event link: [meetup.com event](https://www.meetup.com/Kottans/events/233729023/)

**Comment by sudodoki** [comment]
No idea about what this `Open Learning` means. What is the `program` for meetups?

**Comment by suchov** [comment]
I think about creating a series of meetups and find guys that I can create a course/events with.

**Comment by vessi** [comment]
@suchov, can you edit your issue according to issue template? please take a look on another issues :)

**Comment by suchov** [comment]
ok @vessi

**Comment by sudodoki** [comment]
still not sure what kind of Program could be here 😿 . What's the mission / idea here? Is it going to be series of talks or study course? Who's going to be lecturing/reading those?

**Comment by suchov** [comment]
Don't cry @sudodoki, fixed, hope it's more clear now.

**Comment by vessi** [comment]
@suchov @sudodoki here, i fixed it
