### ISSUE TITLE
Docusaurus

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#40]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [x] Other

By/for
+ [x] kottans
+ [ ] non-kottans

Subject: Finish work on Docusaurus project

Term/duration: none

Keywords: online, website with documentation

Basic list of content https://telegra.ph/Spisok-kontenta-dlya-dokuzavra-02-22

In order to provide access to website, @Croftyland should publish it and then we will check information on it.

**Comment by Croftyland** [comment]
On Friday going to make a first glance at the site

**Comment by Croftyland** [comment]
@AMashoshyna plz check articles
@OleksiyRudenko  here repo where you can fill issues [kottans|docu](https://github.com/Croftyland/junior)

Sonner will fix 
• animation 
• pictures in youtube 
•  add .md file with all activities in telegram

**Comment by Croftyland** [comment]
Finished the project 

@zonzujiro, can I close the issue?

**Comment by zonzujiro** [comment]
@Croftyland didn't saw the comment. Sorry.

Thank you very much :) Let's close it!
