### ISSUE TITLE
Facebook Communities program

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#41]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [x] Other

By/for
+ [x] kottans
+ [ ] non-kottans

Subject: Consider partnership in Facebook Community Leadership Program

Term/duration: none

Keywords: online

In order to become a participant in a program, we should send a letter to FB and get a list of requirements from them. Also, we need to obtain more information about the benefits that can be provided by FB.

After this, we will consider our future steps.

**Comment by suchov** [comment]
https://communities.fb.com/about-the-program/
https://communities.fb.com/faq/ - This is the pilot year of our residency and fellowship programs. Please stay tuned for upcoming opportunities to apply.

**Comment by suchov** [comment]
As I remember the Idea was to keep working with all the marketing channels that we have, config the cross-posting for the FB and see how it goes then? 
Will it work for now or should we close this issue and just keep working with FB just as a news feed...

**Comment by zonzujiro** [comment]
Yes, I had the same idea. Let's focus on developing the group for now.
