### ISSUE TITLE
Create rules for Radio Kottans

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#42]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [x] Other

By/for
+ [x] kottans
+ [x] non-kottans

Subject: 
- [x] rules and example of description for vacancies @zonzujiro 
- [ ] rules for links which will be posted in Radio @AMashoshyna 

Term/duration: none

Keywords: online

**Comment by zonzujiro** [comment]
Rules - https://telegra.ph/Pravila-Radio-Kottans-02-29

**Comment by AMashoshyna** [comment]
I like the rules! Should we maybe elaborate on the first paragraphs just a little?

Ми хочему бути впевненими у вакансіях, які оприлюднюємо на нашому каналі, тому вакансія має відповідати одному з цих правил:
1.
2.
3.

Також, опис вакансії має бути у human friendly форматі. Просимо описати вакансію власними словами у вільній формі, не копіювати текст з офіційної вакансії. Опишіть, якого фахівця шукаєте (стек технологій, досвід), яку роботу йому належить виконувати (особливості проекту, наисаня коду з нуля чи підтримка існуючої кодової бази), розкажіть про команду та переваги компанії.
Наприклад:

(вакансия Каста)

**Comment by AMashoshyna** [comment]
https://telegra.ph/Pravila-publ%D1%96kac%D1%96i-vakans%D1%96j-u-kanal%D1%96-Radio-Kottans-03-09

Take a look please (not sure if this version is not too verbose)

**Comment by zonzujiro** [comment]
@AMashoshyna great! I agree.
So only rules for links left.
