### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#43]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [x] Other

By/for
+ [x] kottans
+ [ ] non-kottans

Subject: We need to improve our [Patreon](https://www.patreon.com/kottans) page and start collecting profits!!!

For this, we should update the page with additional information: description of the community, add nice looking pictures and description of how patreons can support us. 

After this:
1. we will place link to the page on our website @zonzujiro 
2. Make posts in Radio and FB with our patreon @AMashoshyna 

Term/duration: none

Keywords: online, PROFIT!!!

**Comment by Croftyland** [comment]
What does it means nice looking pictures? Students? Activities? Platform project? Logo of kittens in different versions?

**Comment by zonzujiro** [comment]
@Croftyland I don't have anything concrete on my mind right now. What usually is placed in the header of the page at Patreon?

We can take a picture which was used for youtube channel and FB page, if you want.

**Comment by Croftyland** [comment]
@zonzujiro, I will leave here some basic ideas about how they should look like after finishing docusaurus

**Comment by zonzujiro** [comment]
In general, I see our tactic with patreon in two ways:

### Easy go - mostly for alumni and those, who already know us in person

Update the current page with fresh content. We can use our default description, picture from youtube cover or else. Funds can go on coffee, stickers, t-shirts, anything else. Or probably something funny, like "Pay like kitten", "Pay like might Kottan", etc.

Then we can start to promote the page here and there.

This is a fast approach - we will not spend additional time on it and, probably, will receive some small income.

### Hard way - everyone?

Make something like Prometeus [done](https://www.facebook.com/prometheusmooc/videos/193573825198810/?__xts__[0]=68.ARAbWE-24cfswzOlnSpQl5BR1EpLSCw1pQPcyhPjRmn6BU4BTeirqrqhP5mc3BXb7u57qp4Y1XZdVbGHpkHwcnsKVT_pGQbIFVOI3L7rc4kufQtBeD5ckNqhYXx5ZCZfZ7HLNQV_j-IipS23ybP5oOo7RrfsPnyXxuvjbhysBZybIMAMf4jfCwN8es3UnvvDzkEul_MdnPMk-rx16TvXm-9V8R9mdqm8T1lhHf9KVpr-3ax-J3l1dwvHHum2i8Z58Tj6TWMrawN7ZdnSHPAv03DuAkjOvg827l2o1wH7NL5dYy5MqOynY-98Iavs3OOk5Gb22fnPav0C3uftUyz20xxFUmYTTLr_Q46a9_OnA9ux2mfvfKlw3ERKNAye321T&__tn__=H-R).

I mean:
- Create a full description of us
- Describe what we have done and provide links to youtube and courses programs
- Describe our nearest plans
- Describe on what exactly we will spend money
- Probably also make the video, but with @suchov, Roman, maybe me and couple of students

We will spend **a lot** more time. But I don't know how this time will increase the possible income.

So, looking for your opinion @kottans/core

**Comment by Croftyland** [comment]
Definitely we take a hard mode. I will explain why. 
Firstly, it’s obvious that one day we are going to think about global plans like Prometheus did. Why we should think and redo work twice?
Secondly, all steps which you mentioned we should do them. All of them are useful for success and full understanding of who we are and why we need it.
Thirdly, I think about @suchov and Roman to take a part in this project. But also to ask sudodoki, listochkin and other celebrities who taught in kottans.

**Comment by Croftyland** [comment]
https://docs.google.com/document/d/1-NUNuqHcayaDuqbS4lI6GdQdgaDrq73LxcHNQTCqmtY

Can you please check text and give your opinion about it

**Comment by zonzujiro** [comment]
LGTM. I can tell about the Platform, conferences and other activities.

**Comment by Croftyland** [comment]
Don’t forget that video should be less than 40sec. I saw video about Prometheus. It was completely boring and it was enough for me turn off less than 1 min

**Comment by zonzujiro** [comment]
What timing I have?

**Comment by Croftyland** [comment]
Add text which you want to hear in promo. Just want to mention that it shouldn’t be huge and filled with accurate information.

**Comment by Croftyland** [comment]
@zonzujiro @OleksiyRudenko how have you synchronized microphone and video during input promo-videos?

Is it possible to get the result by OBS app?

**Comment by zonzujiro** [comment]
@Croftyland we have connected microphone and camera to notebook thru OSB

**Comment by Croftyland** [comment]
@OleksiyRudenko is it possible to get microphone next time?

**Comment by OleksiyRudenko** [comment]
1. Will have a mic next time. Please note, it requires USB type A socket.
2. FYI OBS setup we used for streaming and stream recording: https://gist.github.com/OleksiyRudenko/183e6177c44a9854d39445825083bda1

**Comment by zonzujiro** [comment]
I have an adapter from Type C, if smth

**Comment by Croftyland** [comment]
I have passed all instructions but better to have extra computer. Thanks @zonzujiro and @OleksiyRudenko

**Comment by OleksiyRudenko** [comment]
@Croftyland what do you mean by "extra computer"? The point is to have the entire setup on a single device

**Comment by Croftyland** [comment]
@OleksiyRudenko, I meant that if something went wrong, would be great tho have another one for quick change

**Comment by Croftyland** [comment]
Video is ready to get up on stage 

@suchov can you share access for Patreon?

**Comment by suchov** [comment]
done

**Comment by zonzujiro** [comment]
@suchov yes, it is.

@Croftyland thank you for an amazing job!
