### ISSUE TITLE
Create platform chat

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#44]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [x] Other

By/for
+ [ ] kottans
+ [x] non-kottans

Subject: We should gather leaders of other communities in one chat in order to:
- solve problems with clunches
- create one place where anyone can find someone for collaboration

Keywords: online/offline

For this, we should:

- [ ] Develop rules and description @zonzujiro 
- [x] Create a calendar in google for this chat @OleksiyRudenko 

The above mentioned should be done after an additional meeting on this matter.

Term/duration: none

**Comment by OleksiyRudenko** [comment]
Shareable gCalendar link: https://calendar.google.com/calendar/b/2?cid=aW5wdXQuY29uZkBnbWFpbC5jb20
(based on input.conf@gmail.com acc)
