### ISSUE TITLE
Internal meetup made by alumni

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#47]
**This issue is about**
+ [ ] Course
+ [ ] Conference
+ [ ] Workshop
+ [x] Meetup
+ [ ] Project
+ [ ] Other

**By/for**
+ [x] kottans
+ [ ] non-kottans

**Subject:** A place where participants of the Mentors School which are conducted by @Alimova - https://github.com/kottans/kottans-ongoing-projects/issues/48, can read their lectures.
It probably will happen after finishing of YDKJS course.

**Term/duration:** One-time event

**Keywords:** offline

**General description:** Participants of Mentors School need a place, where they can apply their skills received in this school. Because of one of the skills - public speaking, we can conduct local meetup, made by alumni and for alumni.
In the end, we should have videos with lectures, postmortem, and photos.

**Comment by zonzujiro** [comment]
@Alimova pls, provide a list with lecturers and topics.
Also, I gave basic descriptions from what you told me. If you find that something wrong or there is a lack of information - fill free to change it.

**Comment by Alimova** [comment]
Work In Progress:
Scrum for Kottans by Anna Alimova
Grids workshop by Vlad Vorobyov
more details to follow

**Comment by zonzujiro** [comment]
Instead of meetup we will organize open mic for alumni of this course - https://github.com/kottans/kottans-ongoing-projects/issues/51
