### ISSUE TITLE
Kottans Mentors School

### ISSUE THREAD

**Issue by Alimova** [kottans/kottans-ongoing-projects#48]
This issue is about

- [x] Course
- [ ] Event
- [ ] Project
- [ ] Other

By/for

- [x] kottans
- [ ] non-kottans

**Subject:** Course for future Kottans mentors who would hold the next front-end course Sep 2020-May 2021

**Term/duration:** February 1st 2020 - September 1st 2020

**Keywords:** offline, Kiev, JS, soft skills, mentoring

**General description:** 

**Aim:** course has in mind learn mentors who can handle next frontend that starts in September 2020

**Skills:**

1. hard skills: theory, livecoding, javascript in depth, principles of modern frameworks, patterns, tasks decomposition, test automation

2. soft skills: public speaking, mentoring, explaining information in convenient and understandable way, self-management

**Flow:**

* Public speaking - during all course every participant trains ones public speaking skills. From very beginning we do this within group. Next iteration is one-time lectures/workshops within Kottans platform. Next step may be a speech in external conf/meetup.

	**What we do:** participant chooses topic that he/she likes to share most. We listen and provide detailed feedback + video for self-control. Work carefully on individual development. 

	Expected result: being able to handle any type of audience and let them undertand taught information deeply

* Course program grooming - update program the way that would help to meet participants and employers needs the best.

	**What we do:** gather feedback from alumni in following format:
	* what was the most useful in course for you?
	* what was missing and you'd like to add?
	* what was the most vibrant you remember form the course?

	Analyze feedback from employers who hired devs after kottans course

	Talk to senior devs and ask to comment and advise what can be better

	Expected result: updated course plan and deep understanding of what should be taught and why, learn what course consists of and list of skills they have to gain to teach.

* Seniors interaction
	There are few steps to involve senior developers into course mentoring:
	* invite seniors to **hold a speech** how they got where they are, share approach, best practices in learning and success stories
	* invite seniors to **help grooming course program** and help make it better and more convenient for learning what was announced
	* invite seniors to mentor *Mentors School course participants* in developing their teaching plan and help in certain questions for specific topic (ideally, one senior mentor per lecture, every course participant interacts with few seniors) + take part in certain *Frontend Course 2021 lecture* itself as backup for unattended questions from youngsters.

* Automate code review - create linter and autotests for every frontend course task in order to make check fast and efficient - mentors only look into code when it is properly formatted and provides expected result.

**Number of participants:** up to 10 people
**Format:** we meet every week (every two weeks until YDKJS ends) for activities listed above. We focus on initiative and letting participants reach their own aims through contributing into Kottans.

**Comment by Alimova** [comment]
Report 06.02.2020
What was done:
- first speaker shared success story about how he became Kottans mentor - there was only course program and he was not experienced enough but engaged participants to look for answers together. 
This encouraged mini-mentors not to stuck into their incompetence but go forward and try.
- brainstorming of how they see next course and what hey like to include
Home task for next meetup:
- write down what they understood from brainstorm and how they see next course program.
- choose topic for speech

**Comment by Alimova** [comment]
Report 26.02.2020 - public speaking
Vitalik, Dasha and Vlad help speeches on chosen topics, got feedback and are planning to re-do these into bigger lectures for open audience
An idea of program grooming and code review automation was presented.
Home task: 
Vlad - preparing workshop about grids for public speech within Kottans
Alex & Bodya - preparing 15 min speech for next meetup
others - gathering feedback from previous course finishers

**Comment by Alimova** [comment]
Plan for 12.03.2020
- штмшеув Anastasiia Chepka to hold success story spech
- listen and discuss speeches from Alex & Bodya
- discuss course feedback and make plan of what should be improved to meet expectations + clone current course repo and start improving it
- review current online course tasks and choose tools for whiting auto-tests (discuss an idea of hackaton)

**Comment by Alimova** [comment]
Plan for 26.03.2020
Invited Stas Gavrylov to hold a speech with success story

**Comment by zonzujiro** [comment]
@Alimova great job! Thank you for the detailed description. Excited and looking forward to update :)

First of all - this is a **lot** of job. So if you will fill, that you need some help - pls, contact me ASAP.

Couple thoughts:

>  course has in mind learn mentors who can handle next frontend that starts in September 2020

Probably they can help us with some minor lectures or smth. Not something major, like framework.

> Analyze feedback from employers who hired devs after kottans course

This should be done by students? How they will get feedback? Ask their team leaders/PM?

> Talk to senior devs and ask to comment and advise what can be better

Let's think about this because **every** senior developer will have an opinion about **every** part of course. So if we really will ask something like this, we should understand, that we have the last word on every matter about course.

> Automate code review - create linter and autotests for every frontend course task in order to make check fast and efficient - mentors only look into code when it is properly formatted and provides expected result.

Pls, contact me when you will be ready to conduct this one. We should agree on the rules of linter and Cetera. Also, probably @AMashoshyna can help you with the environment.

> write down what they understood from brainstorm and how they see next course program.

Do you have some place, where they put all their ideas? Some GoogleDrive or something like this? It could be interesting to read to understand quality of their feedback.

> invite seniors to mentor Mentors School course participants in developing their teaching plan and help in certain questions for specific topic (ideally, one senior mentor per lecture, every course participant interacts with few seniors) + take part in certain Frontend Course 2021 lecture itself as backup for unattended questions from youngsters.

Seniors will be as a backup? Didn't understood.

> Number of participants: up to 10 people

Right now there are 12 members in your chat, along with me and you. So, for now, group are full, right?

**Comment by zonzujiro** [comment]
Also, what you say, if we will have some sort of weekly or once in two weeks meeting or call, as an example, for a status update?
Or you can do it in a way which is more comfortable for you.

**Comment by Alimova** [comment]
> Probably they can help us with some minor lectures or smth. Not something major, like framework.
> Seniors will be as a backup? Didn't understood.

The point is to prepare mentors course attendees to be able to hold lectures by themselves. The entire idea of involving seniors works for this.
Why: there is lots of technical and organizational work around holding lectures. I believe that would not be the right usage for seniors skills just making them give lectures. I want them to mentor future lecturers to hold lectures in highest standards by:
1. helping to gather and prepare materials
2. Answer questions while digging into topic
3. Listen, explain and make corrections
4. Attend lectures and give hints while mentor course students are on the stage
5. Help answering questions from audience if needed
By this we unload seniors from unnecessary technical work and at the same time give our students a powerful tool to improve their skills by constant interaction with personal senior mentor. Meanwhile senior gets interesting interaction with person who is motivated and is up to topic.

>Let's think about this because every senior developer will have an opinion about every part of course. So if we really will ask something like this, we should understand, that we have the last word on every matter about course.

You're right, I have to think about it. First idea is to show them general plan and ask if they would be satisfied if get junior/trainee with this number of skills. And their ideas of how to measure skills. I don't think there is any point to involve seniors in re-doing course in general. I'd better ask one to co-operate with Kottans young mentor instead to make topic work really good.

> This should be done by students? How they will get feedback? Ask their team leaders/PM?
Good point. I'll ask them to talk to their team leads. Yet I planned they'd help me asking their co-learners.

> Right now there are 12 members in your chat, along with me and you. So, for now, group are full, right?
There is @OleksiyRudenko too )) So we have some space )) Yet I am not sure about several members if they are ready to move on. We have team of 5 members who attend every class and it is going to come to stability during first 3-4 meetings. 

> Pls, contact me when you will be ready to conduct this one. We should agree on the rules of linter and Cetera. Also, probably @AMashoshyna can help you with the environment.

I want do discuss with guys first. I would say we should set up infrastructure first and proper configs could be set up during longer period of time.
As far as I can see, node-homeworks uses Travis. To be honest I had semaphoreci in mind, it's free and powerful enough.

Best way to handle this would be kind of hackaton for mentors course students.

> First of all - this is a lot of job. So if you will fill, that you need some help - pls, contact me ASAP.
I do understand responsibility. But I also have at least 6 people who do their best. I mostly inspire and co-ordinate them, as the main point of course is to grow responsibility and initiative in them.

**Comment by Alimova** [comment]
> Also, what you say, if we will have some sort of weekly or once in two weeks meeting or call, as an example, for a status update?
> Or you can do it in a way which is more comfortable for you.

Works for me. I consider the most convenient way as two steps:
1. Writing report and plan for next events
2. Discussing the report in personal (rather online or offline depending on ongoing activities)
Saturday in Star looks good for next few weeks. Let's try how it goes.

**Comment by zonzujiro** [comment]
So summary meanwhile:

I DO agree with lectures by mini-mentors, but only simple ones. They do not have skills for hard technical things. Even with the help of seniors, they have a lack of experience and because of this, the level of talk itself will be low. Probably let's discuss this one more time at Saturday.

> First idea is to show them general plan and ask if they would be satisfied if get junior/trainee with this number of skills.

I prefer not to stick to opinions only from seniors if possible. @OleksiyRudenko had an idea to ask requirements from companies also. But I am not sure about format how to do this.
Also, you should understand that showing just the list of topics from the course will not say a lot. You will need to provide information about what knowledges they should have after the lecture.

> Attend lectures and give hints while mentor course students are on the stage
Help answering questions from audience if needed

So senior should be during a lecture as a guest?

**Comment by Alimova** [comment]
> I DO agree with lectures by mini-mentors, but only simple ones. They do not have skills for hard technical things. Even with the help of seniors, they have a lack of experience and because of this, the level of talk itself will be low. Probably let's discuss this one more time at Saturday.

You're right, they are not ready yet. But we have time till September for them to gain experience. We'll have enough information to solve if they are ready before the course starts. My idea was to let them practice their teaching skills to make them good enough. Let's see how it works.

Meanwhile the general idea of involving seniors consists of several steps:
1. We first ask for minor help such as share success story
2. Depending on how they feel about contributing into Kottans, we involve them into deeper activities such as mentoring Kottans Mentors course participants. 
3. Then option to engage them to hold lectures for complex topics depends on their interest and care we can provide.

But general idea is we have to go step by step, track and meet their needs in mentorship. That is proper way to build partnership.

The second concern is that expert does not mean good teacher. Thus, seniors may be really great as mentors for kottans alumni but not very useful as lecturers as they see no point in paying attention for developing their teaching skills. Meanwhile current course has teaching skills as one of key points.

Another reason why I believe this would work better is the common problem all frontenders have which is imposter syndrome. What we actually offer seniors is to tame their concerns and feel themselves real experts. Meanwhile teaching is stressful, risky and makes you feel even worse while you preparing lecture. One really needs strong support in order not to give up and stay focused. I can handle this for particular group of 6 people who meet every week, but trying to cheer up all of our senior mentors who do this by their own... ugh... that usually just make them feel they are not good enough and they reject to go on with us.

**Comment by zonzujiro** [comment]
> Thus, seniors may be really great as mentors for kottans alumni but not very useful as lecturers as they see no point in paying attention for developing their teaching skills. Meanwhile current course has teaching skills as one of key points.

You just targeting another type of seniors. No need to merge them, IMO.

The first type - lecturers. We can read parts as a framework or vanilla js by ourselves. The second - is personal mentors. And this is your group.
If someone from second group will have a desire to come into first - ok. It would be good. If no - not a big problem.

> Another reason why I believe this would work better

Not sure what you comparing here. Can you please clarify what you mean under the better? Better than what and for what? Then just throw the mini-mentors into course?

**Comment by AMashoshyna** [comment]
As an idea: on Coursera and similar MOOC-platforms there is a concept of teaching assistants (TAs). Those are young teachers who support main lecturer's work:  monitor forums and answer questions they can (or forward them to the professor), help solving any setup problems etc. In CS50 they also make short explanatory videos which support main lecture. 
I believe we can take this model for our mini-mentors: the lecture will be held by invited senior developer and then all of the questions and clarifications will be done by mini-mentors. Their responsibility will be basically to deeply understand the lecture and explain as much times as needed to the students6 answer questions in chat, help with homework etc.
