### ISSUE TITLE
Watching party for CWO

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#49]
**This issue is about**
+ [ ] Course
+ [ ] Conference
+ [ ] Workshop
+ [ ] Meetup
+ [ ] Project
+ [x] Other

**By/for**
+ [x] kottans
+ [ ] non-kottans

**Subject:** Pre-record the talk.

On the day, invite the speaker and attendees to a chat channel (Slack, Twitter, etc..) Speaker answers questions live in chat while attendees are watching the talk.

Bonus: publish the Q&A.

**Term/duration:** don't know

**Keywords:** online/offline, Kyiv, company culture, technologies, business

**General description:**
I have two topics and several questions around each one and I want to know answers on them.
We can try to find someone who has enough expertise and read a small lecture or share thoughts on a matter on camera.
Then, we can arrange a gathering of people - team leads, product managers, CWO, etc. to show these videos and ask questions to the lecturer.

I will leave a description of topics and questions later.
Then, we will have a possibility to understand can we find someone who can tell us something interesting about it.

**Comment by zonzujiro** [comment]
# Ukraine is "outsource country"

## Short story

Ukrainian IT companies are mostly working as outsource for the USA, EU, etc. So, as a consequence, we don't have product culture in our country similar to Israel, as an example.

This brings us to the fact, that we have our specific problems. As an example:
- developers don't have a culture of owning the product - all problems are not problems of mine but of the client, so if something will fail - this is because a client has wrong processes, bad QA, bad management, etc. Instead of solving the problems of your product, developers strive to blame the situation and trying to find who is guilty;
- it is hard to find good managers, especially product managers. Existing PMs works mostly in outsource companies and have a little experience in shipping the product from scratch;
- an average salary of a developer is higher than the salary of a product manager, because of this there is a little amount of PMs with a technical background. Mostly are with marketing or sales past;

## Situations

**You want to find a remote team in Ukraine for your product**
- what qualities you will look for in developers and managers?
- what information do you require to make a decision?
- from what sources and from where you will start?

**You will manage a remote team in Ukraine**
- what problems should be solved by the team itself and what problems should be raised to you?
- what most effective model of communication with a remote team in Ukraine, from your experience?

## List of general questions:
- how effectively manage a team of developers in Ukraine sitting in EU, USA?
- what characteristics of a chief officer or product manager in Ukraine should have?
- what gaps exist between two working cultures - Ukrainian and EU, USA?
- what common problems we have as Ukrainians? Something shared between all or most of the companies
- what issues will face a middle line manager of the client in work with a remote team in Ukraine?
- what or strong sides? In developers, in management, etc.

**Comment by zonzujiro** [comment]
# Custom technical solutions

## Short story

Sometimes we make choice - use existing library/framework/solution or develop own. What problems has a homemade inner product from point of view of business?
I mean not a tool, but more like general stuff. Alternatives for React/Angular, Redux, etc.

## Situations

**Your developer comes to you and asks your opinion about implementing a homemade solution instead of an existing library.**

- What information he should provide?
- How you will build a list of requirements which should be followed by this solution?
- What possible future problems you will try to understand while making a decision?

**You need to sale this approach to business owners**

- What process of taking such decisions is most comfortable for you, business?
- What information you should provide for owners?

## List of general questions:
- is it hard to find developers for a solution that is based on the inner product?
- what problems will arise in the future from such a product?
- what should be taken into consideration when a company will choose to develop own solution?
- how to understand that existing solution cannot be used - what metrics we should gather and how?
- how to create an acceptable learning curve for homemade solution?
- what good practice we should take into consideration while developing a product?
- how to effectively teach developers in the company to use a product? 
- how to generate and save good practices?
- how to determine which features should product have and which don't?
- is there some specificity in organizing the team who develops inner product?

**Comment by zonzujiro** [comment]
A general idea, for now, is to take two HR's and with their help generate some topics which can be interesting for lectures and helpful for listeners.

HR from Preply already agreed to take part in this activity. They have managers who worked in Booking and SkyScanner and probably will be glad to tell something on camera.

Also, I will speak with another HR, which also working in some product company. 
After this, I will create a chat and make kick-off for them.

Meanwhile, pls think about possible topics. 

@such7 @OleksiyRudenko

**Comment by zonzujiro** [comment]
Added general situations to descriptions, just to provide some context to questions.

**Comment by OleksiyRudenko** [comment]
@zonzujiro pretty good progress, grats.
As for the topics I can see approaches as follows:
1) what listeners would like to learn/know (hey guys, we're gonna have Jeff Musk, Bill Jobs and Sergey Zuckerberg online somewhere in mid-April; what would you like to learn from him?)
2) what a CWO wants to tell (hey Jeff, we're gonna gather 100500 Ukrainian devs somewhere in mid-April; is there anything you'd like to tell them?)
3) a combo of 2 above: first item (1) then "hey Jeff/Bill/Sergey, we're gonna gather 100500 Ukrainian devs somewhere in mid-April; they are interested in topics A, B, C. Are you interested in speaking on any of those?"

@suchov

**Comment by zonzujiro** [comment]
Example of format https://twitter.com/lunivore/status/1237383325045710848

**Comment by zonzujiro** [comment]
@OleksiyRudenko I also hoped that you can share some situations from your personal experience :)
