### ISSUE TITLE
Kyiv SICP study group

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans-ongoing-projects#5]
This issue is about 
+ [ ] Course
+ [ ] Event
+ [ ] Project
+ [X] Other [Study Group]

By/for
+ [X] kottans
+ [x] non-kottans

Subject: Study group / reading club to go over [SICP](https://en.wikipedia.org/wiki/Structure_and_Interpretation_of_Computer_Programs) and exercises.

Term/duration: depends on pace of reading. Initial assumption – we go with one 'section' (second level numbering comprising 1.1-1.3, 3.1-3.5, 2.1-2.5, 4.1-4.4, 5.1-5.5) a week - it will take 22 weeks.

Keywords: offline, Kyiv, reading club, computer science, intro level, english

We don't have a stated venue for this.

We don't have schedule set for this. I assume we should be doing reading during the week and gathering once a week, for example, on Thursday evening (19:30) and going over exercises/discussing questions, etc.

Unless someone drops out by 1st of september, participants are as following:

+ @sudodoki
+ @firec0der 
+ @vessi 
+ @robobee
+ @AlexMost
+ @vharitonsky
+ @jetmind  (? given halfway done)
+ @ElegantElephant44

**Comment by sudodoki** [comment]
Start date is going to be (supposedly) September 1st (because it's thursday and day of knowledge)

**Comment by sudodoki** [comment]
Write here if you are interested. I believe, this would be first come / first serve type of thing and main coordination will be either in gitter or skype – we'll figure it out later.

**Comment by sashashakun** [comment]
Such a great idea. I would participate with pleasure, if I lived in Kiev. Unfortunately, I am not. So, good luck, guys!

**Comment by KBoyarchuk** [comment]
Like Kottan who lives in Kharkov would gladly participated, if there was such a possibility.

**Comment by vessi** [comment]
I am in

**Comment by programulya** [comment]
If you start 'Algo' books I'll join, ping me please if you have any plans about this 👍

**Comment by firec0der** [comment]
![oenguin](http://i.giphy.com/Y81Q5iFwJj8qs.gif)

**Comment by robobee** [comment]
Great idea, guys, I'd love to participate!

**Comment by sudodoki** [comment]
https://twitter.com/darkproger/status/765189330637905921

**Comment by sudodoki** [comment]
@robobee please, send me an email to smd.deluzion@gmail.com, need some way to communicate with you other than github

**Comment by AlexMost** [comment]
I'm in !

**Comment by jetmind** [comment]
I'm interested too! Though, I'm halfway through the book already.

**Comment by vharitonsky** [comment]
+

**Comment by sudodoki** [comment]
@jetmind @AlexMost @vharitonsky same request as in https://github.com/Kottans/kottans-ongoing-projects/issues/5#issuecomment-239848759

**Comment by ElegantElephant44** [comment]
I'm interested!

**Comment by sudodoki** [comment]
@ElegantElephant44 please, follow https://github.com/Kottans/kottans-ongoing-projects/issues/5#issuecomment-239848759

**Comment by sudodoki** [comment]
I think that would conclude the people for the group. You are welcome to do same thing in different [thread](https://github.com/Kottans/kottans-ongoing-projects/issues/new) if you want to. Coordination for this issue will go through other means (email and then some group chat if everybody agrees), thus I'm closing this issue.

**Comment by sudodoki** [comment]
Everyone in the list in the issue's text should have gotten an email with details of the first (zeroth?) meeting.

**Comment by sudodoki** [comment]
We have finished the book. It took us 7 months 8 days to complete, accounting for missing meetings / rescheduling / repeating same chapter on multiple meetings. 👍 thanks to everyone involved.
