### ISSUE TITLE
RFC: Summary Frontend Course

### ISSUE THREAD

**Issue by zonzujiro** [kottans/kottans-ongoing-projects#50]
**This issue is about**
+ [x] Course
+ [ ] Conference
+ [ ] Workshop
+ [ ] Meetup
+ [ ] Project
+ [ ] Other

**By/for**
+ [x] kottans
+ [ ] non-kottans

**Subject:** We should formalize summary about FE course

**General description:** 

## Weak spots

- Low level of technical knowledge of alumni
- To much work with code review during offline and online part
- There are some redundant lectures in the course - Canvas, WebSocket, etc.
- To much work with answering the questions from students
- Missed DOD for the course and each lecture 

## Feedback

- we should add practice with TypeScript
- possible we should consider adding more practice about Git, as which was conducted by @OleksiyRudenko
- probably, we should consider adding the final project as DOD, instead of tests
- lecture about Agile and Scrum
- Luck of tests. Maybe even TDD

**Links to sources of feedbacks:**

1. https://docs.google.com/spreadsheets/d/1OZ-sEsXm-6dCKR9Rn_21MGPU4yJX8eE8Lf4buvThMxs/edit#gid=0
2. https://drive.google.com/drive/u/0/folders/1_9i6rzo8wRvHwCuukaUd1XcCLNmcQx88

### Configure environment

We should add linter and prettier checks, like for Node course. Also, we should add unit tests for tasks in the online part.

### Methods of entities

Students don't know standard methods of JS API, so we should add tasks in which they will need to create such methods - `Array#map`, `String#replace`, etc. 
As an example of such a task, we can take workshop about `Promise` which is made by @yevhenorlov.

### Replace redundant lectures

In current realities, students need a general knowledge of JS more, then knowledge of Canvas and WebSocket. So we can replace these lectures with a couple workshops in the format of YDKJS course.

### Change flow of code review

1. PR must be green
2. Then PR should be reviewed by peer mentors
3. After this, mentors will review the rest
4. PR can be merged only by the mentor

### DOD

When we will have a concrete program, we should formulate a definition of done for every lecture or workshop.
This DOD can be made like a test or form with questions.
At the end of the course, we can make the final exam using these questions.

### General view of course

FE course should have more topics related to pure JS.
All lectures should be conducted by real-life JS developers.
Serious lectures, like framework, by seniors.

Also, I believe that for now, in offline part, we should leave only a framework and replace everything else.

In the online part, we can remove Frogger and part of OOP tasks and replace them with tasks related to the creation of standard methods of JS - one for array and string, and one for `Promise`.

Probably we can conduct some lectures or workshops related to soft-skills - how to set and follow goals, time-management, communication with team and management, etc. @OleksiyRudenko what you think? 
Also, I can try to ask some HR to give a lecture about this.

@kottans/core looking for your opinion

**Comment by AMashoshyna** [comment]
> Also, I believe that for now, in offline part, we should leave only a framework and replace everything else.

Do you think having some advanced JS lectures (like Promise workshop last year) would be redundant?

**Comment by zonzujiro** [comment]
@AMashoshyna what advanced JS you have in mind? For `Promise` sync/async from YDKJS can do the job.

**Comment by AMashoshyna** [comment]
@zonzujiro do you mean to use the ydkjs materials for online phase or offline too?

**Comment by zonzujiro** [comment]
@AMashoshyna I was thinking about couple lectures for offline part.

At online - only reimplementing JS API.

What do you think?

**Comment by AMashoshyna** [comment]
@zonzujiro yes, this was my understanding too

**Comment by zonzujiro** [comment]
@Alimova could you please gather opinion from students, so we can analyze it and add to an RFC?

Then, we will understand what to do next.

**Comment by Alimova** [comment]
> @Alimova could you please gather opinion from students, so we can analyze it and add to an RFC?

Started gathering feedback in here: https://docs.google.com/spreadsheets/d/1OZ-sEsXm-6dCKR9Rn_21MGPU4yJX8eE8Lf4buvThMxs/edit#gid=0

List of questions by now:
1. What was the most useful from the whole course in your first job?
2. What knowledge you felt like missing?
3. What is the most memorable from the whole course?

As long as we're planning to upgrade plain JS part I believe I have to add some more questions pointing of that to gather better feedback.

**Comment by zonzujiro** [comment]
@Alimova thank you for the feedback!

Useful information which we can take to consider if we will start a new program:

1. We should add practice with TypeScript
2. Possible we should consider adding more practice about Git, as which was conducted by @OleksiyRudenko
3. Probably, we should consider adding the final project as DOD, instead of tests
4. Lecture about Agile and Scrum. Maybe you can take this one?
5. And tests :) Maybe even TDD. @AMashoshyna can you share your experience from Wix kickstart?

Also, it is good to see, that our idea about peer-to-peer review also was suggested by students.

Have you collected feedback in this sheet? Because I have a feeling, that last column was mostly copy-pasted. Or it was some another mechanism of collective opinion involved. I admire our bar-crawling, costume of Darth Vader and barbeque, but I believe we should gather as much useful information as we can.

So probably you should consider separating feedback about the course and about the day-to-day life of the community. I see two ways to do it:
1. you can split the last question on two - what you like most in the course and in general;
2. or, if feedback collected in sheet, you can replace it with google form.

In the last option, the student also will not see what answered others.

**Comment by AMashoshyna** [comment]
@zonzujiro we had a lot of lectures on testing and TDD in particular, starting from FizzBuzz and ending with Puppeteer

**Comment by zonzujiro** [comment]
@AMashoshyna it would be great to adapt something from them. But we don't have so much time as on kickstart. Anyway, we should think about it.

**Comment by AMashoshyna** [comment]
@zonzujiro sure, it would be nice to invite lecturers who practice TDD and can teach it.

**Comment by Croftyland** [comment]
I'm preparing now for the interview and making some practical task. If it is interesting for you, can share a repo with theoretical and practical part

**Comment by zonzujiro** [comment]
Yes, share of course. Just remember, that if this repo was provided by company you attend for, such stuff can be private.

**Comment by Croftyland** [comment]
Firstly, I'm showing you. Take feedbacks and then decide how to implement it in our courses.

**Comment by AMashoshyna** [comment]
Many student mentioned that they missed big projects and real-life tasks. I was thinking  what they actually mean by this and how we could give them that feeling, but couldn't come up with an idea. 

Of course, compared to real-life project Weather app lacks the uncertainty, when you need to implement a feature, but don't know the project completely, because it is too big to know. But that's all I can think of.

@Alimova could you maybe ask your group (or event better in Alumni chat to get more responses) for ideas how to make students solve real-life tasks and participate in a big project during course? I can do it myself, just let me know.

**Comment by zonzujiro** [comment]
@OleksiyRudenko provided link to feedbacks after lectures - https://drive.google.com/drive/u/0/folders/1_9i6rzo8wRvHwCuukaUd1XcCLNmcQx88

I believe we can get some useful info from them also.

**Comment by zonzujiro** [comment]
BTW, instead of reading a lecture about TS, we can try to build all offline course on it. I don't think that it will be too hard for students, because we don't have complex code.

**Comment by AMashoshyna** [comment]
That's what we did a Kickstart - just started with TS and did all other subjects based on TS code

**Comment by Alimova** [comment]
> @Alimova could you maybe ask your group (or event better in Alumni chat to get more responses) for ideas how to make students solve real-life tasks and participate in a big project during course? I can do it myself, just let me know.

They expect project they build not from scratch but have a chance to dig into code someone else written and alter it. They expect to collaborate and work in groups. Maybe some kind of graduation project. Or kind of open source hackaton.

**Comment by Alimova** [comment]
> 4. Lecture about Agile and Scrum. Maybe you can take this one?

Anytime our students are ready. I would suggest to hold it nearest time when quarantine is over.

**Comment by zonzujiro** [comment]
> Anytime our students are ready. I would suggest to hold it nearest time when quarantine is over.

I mean during a course :)

> They expect project they build not from scratch but have a chance to dig into code someone else written and alter it. They expect to collaborate and work in groups. 

> Or kind of open source hackaton.

It will be hard to produce something like this by ourselves. Maybe really some OSS project, but they usually have quite simple tasks - fix translation, fix codestyle.

> Maybe some kind of graduation project

That was my idea also.

> That's what we did a Kickstart - just started with TS and did all other subjects based on TS code

@AMashoshyna but you had some introduction lecture, right? Then simple pet-project and we are ready to go?

**Comment by OleksiyRudenko** [comment]
> Then simple pet-project and we are ready to go?

Community calendar? 
- Google Calendar API
- GCS hosting
- DOU, AIN et al scraping
- finally, nice alternative Google Cal web-client with subscription, filters, and Black Jack

**Comment by Alimova** [comment]
Guys, may we involve them in some kind of Kottans needs? Such as new tool for us. I would suggest something that works with GitHub API such as analytics that shows progress on pull requests. The tool we always wanted but never had time for. I believe this would inspire them and give a good peace of collaboration and experience.

**Comment by zonzujiro** [comment]
Ehm... we wanted some tool? Do you have something more concrete in mind?

**Comment by AMashoshyna** [comment]
Do you see it as a replacement for some task or as addition to existing program?
I would suggest to move towards tasks which are easily tested automatically. With this task since we do not have a unified UI I hardly imagine we can write tests.

**Comment by Alimova** [comment]
I see it as a graduation project by the end of the course. This is not one of common tasks, every year will got their own

**Comment by sudodoki** [comment]
based on what I previously encountered, best experience with final project was not when everything on project had to be done in some specific timeframe right before graduation, but some time was spent during whole course, with some homeworks being specifically about coming up with the project, repeating thing similar to homework but for the project (like setting up linters/builders/etc for both home assignment and specificly for a project), or specifically having homework task be done in project (if applicable, and on some default dummy project/task in other case) and maybe be easier with tasks in the end, giving people more time to focus on final project. Which still might be a high bar to aim for people with less experience. + if students hit the roadblock sooner, they will have time ask mentors advice on the issue, not causing too many questions asked at the same time if everyone starts the project at the same time.
