### ISSUE TITLE
Fall 2016. Workshop @ Kharkiv JS

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans-ongoing-projects#6]
This issue is about 
- [ ] Course
- [X] Event
- [ ] Project
- [ ] Other

By/for
- [ ] kottans
- [X] non-kottans

Subject: suggestion to conduct paid workshop at KharkivJS

Term/duration: One day (first half of November)

Keywords: paid workshop, offline, Kharkiv

Let's discuss this as community as I'm not sure how this would work given we are doing free stuff. Possibly, find someone who would do this but not under kottan logo/trademark

**Comment by vessi** [comment]
this definitely should not be done under Kottans umbrella. we are principally free.

**Comment by sudodoki** [comment]
Agreed, do you think I should put this off the agenda for call? Maybe, someone would be ok to pick it up?

**Comment by vessi** [comment]
putting this off the agenda for the call means that noone will even take care of this. let's leave this in agenda, this will increase chances to perform event

**Comment by sudodoki** [comment]
![image](https://cloud.githubusercontent.com/assets/1506905/21741759/e1d0bb6e-d4e8-11e6-8967-a28e28e23886.png)

Well, we didn't do anything long enough and we don't need to anymore.
