### ISSUE TITLE
Next JS Course

### ISSUE THREAD

**Issue by sudodoki** [Kottans/kottans-ongoing-projects#7]
This issue is about 
- [x] Course
- [ ] Event
- [ ] Project
- [ ] Other

By/for
- [x] kottans
- [ ] non-kottans

Subject: next JS Course placeholder 

Term/duration: whatever team decides to

Keywords: offline, Kyiv, JS

Regarding students level: 
- can be either jun-to-middle as we had on previous courses
- can be just juniors
- can be middle-to-senior, with focus on widening the horizons

We are building up team:
- [x] @shvaikalesh 
- [x] @suchov
- [x] @m1n0s
- [x] @xanf

…

**Comment by sudodoki** [comment]
This would go into 'consideration' as soon as we get minimal required gang of 2 core coaches + coordinator.

**Comment by suchov** [comment]
nice, @sudodoki !!!

**Comment by sudodoki** [comment]
@suchov I'm not taking part in that (or if I do, only as a guest coach), just created issue on behalf of m1n0s. Do no need to thanks me.

**Comment by suchov** [comment]
thanks @sudodoki I know about you plans, but you are still doing a lot for us!!!

**Comment by mkozhukharenko** [comment]
@sudodoki @m1n0s can you describe details of the course? e.g.: 
- what is a target audience (beginner/advanced)
- duration
- covered topics (in general)

**Comment by m1n0s** [comment]
@mkozhukharenko no, I can't. Cause I only offered my possibilities for help in future course if it will be present. Actually I'm interested to teach other people for front-end, but for now I think that I haven't strong skills in any thin area of front-end (if cource will be advanced) and at the same time html&css&basic js occupied by @shvaikalesh (he said that he always allows for kottans).

But any experience will be nice for me. 

P.S. I don't pretend for be one of core coaches for sure.

**Comment by mkozhukharenko** [comment]
I'd like to be a coach in the course for beginners with a focus on core JS + basics of some framework. @m1n0s, I think you have enough knowledge in this area.
So, @sudodoki, you can count me as well.

**Comment by m1n0s** [comment]
If it will be beginners course - I'm 100% in like a coach. But I think it should be hard hard selection of students because if there were so many strange people for advanced course - I'm afraid of many "Войти в ІТ" people for beginners.

**Comment by mkozhukharenko** [comment]
@m1n0s I'd propose: 
1) make a few small test of which can be checked automatically
2) make first part online (~1 month) with the emphasis on online discussion
3) select the most hardworking for the next offline part
It should help to save a lot of hours (no checking assignment tests 'by hand' and no interviewing).

**Comment by m1n0s** [comment]
@mkozhukharenko I can't answer you now. 
Also maybe @sudodoki know any good advices for beginners courses which can help make it good. Especially I didn't like online part, because is sooo much information for beginners in web.

Maybe we need some pre-advanced course.

**Comment by sudodoki** [comment]
@mkozhukharenko I just added a section on possible levels, but it might be the case you would succeed with creating and gathering along team of coaches for JS101, focusing on creating more beginner-friendly courses, as previously we had feedback that our courses were not beginner enough.

**Comment by suchov** [comment]
I'm just not sure that it should be JS101, Web101 maybe?
I have an idea to create one of those after I'll come back to UA. (December)

**Comment by xanf** [comment]
Hi, guys! I'm in for next JS course and ready be as core and team coordinator.
I'm finishing a big 9-months course on "becoming a better mentor", and would like to try to integrate some practices I've learnt into course preparation, etc. 

I have a prior agreement with @tirli and @Kanuny who are the part of my team with helping. 
Also I'm looking for possibilities to bring Kottans at least to Minsk. It's all about capturing the world :)

I will be busy heavily before Feb 15, so it should be probably be Spring 2017, but I'm definitely in

**Comment by suchov** [comment]
@xanf It's all about capturing the world ;)
I'm in to help with the course in Kiev and can help with thinking about Minsk or Berlin.
Also, I hope that I'll have some experience from https://github.com/Kottans/kottans-ongoing-projects/issues/9 that we plan to start on January

**Comment by mkozhukharenko** [comment]
@suchov can you send a link to the draft of your curriculum? (I saw it one time in the gitter chat)

**Comment by suchov** [comment]
@mkozhukharenko It'll be different from a regular Kottans courses - more self-driven. All that we have for now is in the readme here: https://github.com/kottans/web

**Comment by viattik** [comment]
hey! 
not sure what's status on this.
I would definitely try to participate as both organizer and coach for JS course.
I don't have much experience both in coaching (other than just helping junior guys) and organizing courses, but I would give it a shot if somebody helps me with that and we have a team.

@suchov @sudodoki are you still not interested in leading / consulting this?
@xanf and are you still interested?

**Comment by suchov** [comment]
@viattik will help with all what I can, but considering we have one more course going now - my abilities will be limited, but I can attack alumni, guest coaches, and help with organization. @xanf was interested in making it in Spring as I know + he wanted to bring it to Minsk somehow.

**Comment by xanf** [comment]
Hi @viattik . Yes, I'm still interested in leading this, although it seems that dates will be shifted a bit.

I'm currently interested in organizing some more "core" locations, at least in Dnipro/Ukraine & Minsk/Belarus which may take a bit more time.

In any case, I'm still ready to lead this effort

**Comment by viattik** [comment]
Then let's keep in touch. Just let me know whenever you will be ready.

**Comment by suchov** [comment]
Hey, guys, new registration started: https://goo.gl/tqUtDu
The course will start mid-September.
@shvaikalesh creating a written plan right now, it's in our head yet :)
@viattik @xanf @mkozhukharenko @sudodoki

**Comment by AMashoshyna** [comment]
@suchov @shvaikalesh I'd like to help (I'm good with texts & similar stuff)

**Comment by m1n0s** [comment]
@suchov why you didn't tag me as well? 😸 I'm still interested in telling a few lectures for JS course.

**Comment by viattik** [comment]
I'm still ready to coach and help with organization things.
just let me know what I can do.

**Comment by viattik** [comment]
Also, Rails Reactor has a good room with a projector which we can use. Just approved that.
@suchov @shvaikalesh

**Comment by shvaikalesh** [comment]
@suchov RR's office is far better located, I think we should have courses there.

**Comment by m1n0s** [comment]
@shvaikalesh do you know that they are moved from city centre not long time ago?

**Comment by tilast** [comment]
@m1n0s RR office is not far from Palats Ukraina or Olimpiyska stations

**Comment by m1n0s** [comment]
@tilast Yes, I know :) Anyway it's much better than Cogniance office location. Just want to @shvaikalesh to be familiar with this fact.

**Comment by Avvata** [comment]
Hi, kottans, is it possible to join your Front End 2017 course in Kiev? The registration form is already closed((

**Comment by sudodoki** [comment]
@Avvata no, but you might want to check out #14

**Comment by sudodoki** [comment]
Ok, considering this one done for now as one course in progress, and another one the autonomous one is residing in another issue (https://github.com/Kottans/kottans-ongoing-projects/issues/14 / https://github.com/Kottans/frontend). And some of you might be good fit and have fun mentoring at nodeschool event - https://github.com/Kottans/kottans-ongoing-projects/issues/15
