### ISSUE TITLE
Kottans offline  math club

### ISSUE THREAD

**Issue by Quodnon** [kottans/kottans-ongoing-projects#8]
This issue is about 
- [ ] Course
- [ ] Event
- [ ] Project
- [x] Other

By
- [x] non-kottans

for
- [x] kottans
### [Survey](https://docs.google.com/forms/d/e/1FAIpQLSccSRN0z4jVcJtTO9BogaGXzN4IHbmgs173N7soHdksGmnGiQ/viewform)

Subject:  offline math  courses

Goal: improve kottan's math skills

Term/duration: _unknown_

Keywords: offline Kyiv,  math 
#### Proposition:
- participation in [KPI math club(vk)](https://vk.com/math_olymp_kpi)

> Доброго вечора! 
> Ви можете спокійно ходити на гуртки без додаткових домовленностей. Єдине, якщо Вас запитають, то скажете, що Ви питали і Вам сказали, що можна відвідувати. І то це треба про всяк випадок, бо викладачі ведуть різні і їх може зацікавити хто Ви і звідки.
> Ну і в списку присутніх треба відмічатись і зазнечи звідки Ви. Раз не студенти, то можете вказати фірму. Це нам треба для статистики.
### Time:

every **Tuesday**  
_start_ - **_16:10**_ 
_end_ - **unknown** 
**global end** in the end of study year (May)
### Venue:

KPI 7"th housing, details in [VK group](https://vk.com/math_olymp_kpi)
### Tutors:

authentic KPI staff
## Questions to discuss:
- Time. If inappropriate, then we need to search for alternatives 
- Registration and organization under Kottans tm(if needed)
- more specific target group (i assume that's more suitable for alumni rather than newcomers)

**Comment by Quodnon** [comment]
another proposals for offline 

+ offline group [scala and functional programming course](https://www.coursera.org/specializations/scala)

+ offline group [prometheus dataanalysis course cycle](http://prometheus.org.ua/dataanalysis/) 

>separate into other issues?

**Comment by suchov** [comment]
oh, yes @Quodnon !
You rocks!

**Comment by sudodoki** [comment]
@Quodnon 
>separate into other issues?

Yes, no need to have everything in single issue as it doesn't make sense (would suggest deleting the comment from here at all)

**Comment by Quodnon** [comment]
@suchov @sudodoki  upd in current issue.
> do you see that without direct **@** mention?

**Comment by suchov** [comment]
Nope @Quodnon I don't see without mentioning.
Thanks for an update. Unfortunately, I can join only when I'll get back to Kiev(after 6th of December).

**Comment by suchov** [comment]
@Quodnon is this project still going?

**Comment by sudodoki** [comment]
Considering this inactive.
