### ISSUE TITLE
web course

### ISSUE THREAD

**Issue by suchov** [Kottans/kottans-ongoing-projects#9]
This issue is about 
- [x] Course
- [ ] Event
- [ ] Project
- [ ] Other

By/for
- [x] kottans
- [ ] non-kottans

Subject: Web course

[Not full discription yet](https://github.com/Kottans/web)

Term/duration: whatever team decides to

Keywords: offline, Kyiv, Web, JS, Python, 

Regarding students level: 
- can be either jun-to-middle as we had on previous courses
- can be just juniors
- can be middle-to-senior, with focus on widening the horizons

We are building up team:
- [x] @lempiy
- [x] @suchov
- [x] @tilast
- [x] @zxftr45 
- [ ] @xanf
- [ ] @sudodoki 

  …

**Comment by suchov** [comment]
@tilast @zxftr45 I want to add you guys to this course too. What do you think?

**Comment by zxftr45** [comment]
I think I'm in but no sure how much time I'll have for it

**Comment by tilast** [comment]
same for me, but I will be definitely available for few lectures/workshops

**Comment by suchov** [comment]
thanks, guys
